Add support for enabling kopia web UI
Signed-off-by: Tobias Knöppler <6317548+theCalcaholic@users.noreply.github.com>

diff --git a/bin/kopia-backup b/bin/kopia-backup
--- a/bin/kopia-backup
+++ b/bin/kopia-backup
@@ -13,7 +13,12 @@ create_data_snapshot() {
   restore_maintenance_mode
 }
 
-export KOPIA_PASSWORD="${1?Missing parameter: repository password}"
+[[ "$(id -u)" == "0" ]] && KOPIA_PASSWORD="$(cat /usr/local/etc/kopia/password)"
+[[ -z "${KOPIA_PASSWORD}" ]] && {
+  echo 'Error: KOPIA_PASSWORD not set'
+  exit 1
+}
+export KOPIA_PASSWORD
 
 source /usr/local/etc/library.sh
 
